# Generated by Django 3.2.8 on 2021-11-26 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaAurifono', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoad_avaliacaoad',
            name='DataAvaliacao',
            field=models.DateField(verbose_name='Data da Avaliação'),
        ),
        migrations.AlterField(
            model_name='avaliacaoad_avaliacaoad',
            name='paciente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinicaAurifono.paciente_paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='comunicoral_comunicoral',
            name='dsc_habilidade',
            field=models.CharField(max_length=150, verbose_name='Descrição da Habilidade'),
        ),
        migrations.AlterField(
            model_name='comunicoralidade_comunicoralidade',
            name='ComunicOral_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinicaAurifono.comunicoral_comunicoral', verbose_name='Comunicação Oral'),
        ),
        migrations.AlterField(
            model_name='comunicoralidade_comunicoralidade',
            name='avaliacaoAD_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinicaAurifono.avaliacaoad_avaliacaoad', verbose_name='Avaliação'),
        ),
        migrations.AlterField(
            model_name='comunicoralidade_comunicoralidade',
            name='resp_oralidade',
            field=models.CharField(max_length=1, verbose_name='Resp. Oralidade'),
        ),
        migrations.AlterField(
            model_name='paciente_paciente',
            name='Profissional_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinicaAurifono.profissionalenc_profissionalenc', verbose_name='Profissional Responsável'),
        ),
        migrations.AlterField(
            model_name='profissionalenc_profissionalenc',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='profissionalenc_profissionalenc',
            name='status',
            field=models.CharField(choices=[('1', 'Ativo'), ('0', 'Inativo')], max_length=1, verbose_name='Status'),
        ),
    ]
